version: '3'

services:
  elastic:
    image: elasticsearch:7.10.1
    container_name: elastic
    ports:
    - 9200:9200
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
    - 5601:5601
