# Generated by Django 3.1.6 on 2021-02-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PypiPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.EmailField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('version', models.CharField(max_length=10)),
                ('authors', models.CharField(max_length=255)),
            ],
        ),
    ]
