# Generated by Django 3.1.6 on 2021-05-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypipackage',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
